# Generated by Django 2.2 on 2019-08-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.CharField(default='This is a default Description', max_length=2000),
        ),
        migrations.AddField(
            model_name='note',
            name='imagen',
            field=models.CharField(default='This is a default Imagen', max_length=2000),
        ),
        migrations.AddField(
            model_name='note',
            name='instructor',
            field=models.CharField(default='This is a default Instructor', max_length=60),
        ),
        migrations.AddField(
            model_name='note',
            name='tipo',
            field=models.CharField(default='This is a default Tipo', max_length=30),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='This is a default Title', max_length=200),
        ),
    ]
